phrase:
  project_id: 2ed9148252f5f53ee970c65b6d12732a
  file_format: i18next_json

push:
  sources:
    - file: ./public/locales/en/translation.json
      params:
        locale_id: en
        update_translations: true
        update_descriptions: true

pull:
  targets:
    - file: ./public/locales/<locale_code>/translation.json
